#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Usage: provide a title argument."
  exit -1
else
  title="$@"
fi

slug=$(echo $title | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-')
slug="${slug:0:${#slug}-1}"
post="./_drafts/$slug.md"

body=""
read -d '' body <<EOF
---
layout: post
title: $title
published: true
categories:
  -
---

EOF

echo "$body" > $post
